#! /bin/sh

bspc config border_width        0
bspc config window_gap         16

bspc config normal_border_color "#2F343F"
bspc config focused_border_color "#2F343F"
bspc config active_border_color "#2F343F"

bspc config split_ratio         0.62
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DVI-I-0 -d 6 7 8 9 0

bspc rule -a conky manage=off
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop=8 follow=no floating=on
bspc rule -a streaming_client desktop=5
bspc rule -a Discord desktop=7

bspc config external_rules_command "/home/thilo/dotfiles/config/bspwm/external_rules.sh"

# Autostart
xrandr --output HDMI-0 --auto --output DVI-I-0 --auto --right-of HDMI-0 &
feh --bg-tile "/home/thilo/Bilder/Wallpapers/neist-point.jpg" &
xset s off -dpms &
xsetroot -cursor_name left_ptr &
xinput set-prop 9 135 1.600000, 0.000000, 0.000000, 0.000000, 1.600000, 0.000000, 0.000000, 0.000000, 1.000000 &
bspc desktop -f 1 &
~/dotfiles/config/bspwm/taskbar.sh &
bspc control --subscribe| while read; do bash ~/dotfiles/config/bspwm/titlebars.sh ; done &
~/dotfiles/config/bspwm/adjust_gaps.sh &
compton -cCGf --vsync opengl &
nm-applet & pa-applet & pactray &
redshift-gtk &
unclutter &
dunst &
dropbox start &
discord &
sleep 3 && stalonetray -t --grow-gravity E --geometry 1x1+1845-0 --icon-gravity E -s 32 -i 24 --kludges force_icons_size &
